Repository cisagov/log4j-affected-db, pull requests merged in 2021-12, with the labels that each got.

#162 Fix README to once again pass linting checks
  README.md
Labels: bug

#184 Ensure software list Markdown formatting is both correct and consistent
  README.md
Labels: bug, improvement

#346 Azure/BvD Updates
  SOFTWARE-LIST.md
Labels: need info

#374 Trimble
  SOFTWARE-LIST.md
Labels: invalid

#394 Use issue forms to streamline the issue submission process
  .github/ISSUE_TEMPLATE/product-submission-form.yml
  .github/ISSUE_TEMPLATE/product-submission-template.md
  .github/ISSUE_TEMPLATE/product-update-form.yml
Labels: improvement

#328 Add S3, Circle, and Cloud.gov
  SOFTWARE-LIST.md
Labels: need info

#337 Update SOFTWARE-LIST.md
  SOFTWARE-LIST.md
Labels: need info

#384 Update SOFTWARE-LIST.md
  SOFTWARE-LIST.md
Labels: need info

#412 Use a YAML file to store product information
  .github/ISSUE_TEMPLATE/product-submission-form.yml
  .github/ISSUE_TEMPLATE/product-update-form.yml
  .github/workflows/update_software_list.yml
  .yamllint
  config/SOFTWARE-LIST.tpl.md
  config/requirements.txt
  data/cisagov.yml
Labels: breaking change, improvement

#413 Update the version of cisagov/log4j-md-yml used
  config/requirements.txt
Labels: bug, upstream update

#415 Revert the migration to a YAML format
  .github/ISSUE_TEMPLATE/product-submission-form.yml
  .github/ISSUE_TEMPLATE/product-update-form.yml
  .github/workflows/update_software_list.yml
  .yamllint
  SOFTWARE-LIST.md
  config/SOFTWARE-LIST.tpl.md
  config/requirements.txt
  data/cisagov.yml
Labels: breaking change
