Repository cisagov/log4j-affected-db, pull requests merged in 2022-01, with the labels that each got.

#432 Pull in updates from cisagov/skeleton-generic
  .github/lineage.yml
  .pre-commit-config.yaml
Labels: upstream update

#425 Contributing adjustments
  CONTRIBUTING.md
  PULL-EXAMPLE.md
  README.md
Labels: bug, documentation, improvement

#433 Migrate to using YAML files to store product information
  .github/ISSUE_TEMPLATE/product-submission-form.yml
  .github/ISSUE_TEMPLATE/product-update-form.yml
  .github/workflows/update_software_list.yml
  .yamllint
  config/SOFTWARE-LIST.tpl.md
  config/requirements.txt
  data/cisagov.yml
  data/cisagov_A.yml
  data/cisagov_B.yml
  data/cisagov_C.yml
  data/cisagov_D.yml
  data/cisagov_E.yml
  data/cisagov_F.yml
  data/cisagov_G.yml
  data/cisagov_H.yml
  data/cisagov_I.yml
  data/cisagov_J.yml
  data/cisagov_K.yml
  data/cisagov_L.yml
  data/cisagov_M.yml
  data/cisagov_N.yml
  data/cisagov_Non-Alphabet.yml
  data/cisagov_O.yml
  data/cisagov_P.yml
  data/cisagov_Q.yml
  data/cisagov_R.yml
  data/cisagov_S.yml
  data/cisagov_T.yml
  data/cisagov_U.yml
  data/cisagov_V.yml
  data/cisagov_W.yml
  data/cisagov_X.yml
  data/cisagov_Y.yml
  data/cisagov_Z.yml
Labels: blocked, breaking change, improvement

#444 Update cisagov_I.yml
  data/cisagov_I.yml
Labels: blocked, question

#462 Update the `update_software_list` workflow
  .github/workflows/update_software_list.yml
  config/requirements.txt
Labels: improvement

#465 Restore missing data from the YAML conversion
  data/cisagov_B.yml
  data/cisagov_C.yml
  data/cisagov_D.yml
  data/cisagov_E.yml
  data/cisagov_F.yml
  data/cisagov_G.yml
  data/cisagov_H.yml
  data/cisagov_I.yml
  data/cisagov_J.yml
  data/cisagov_K.yml
  data/cisagov_L.yml
  data/cisagov_M.yml
  data/cisagov_N.yml
  data/cisagov_O.yml
  data/cisagov_P.yml
  data/cisagov_Q.yml
  data/cisagov_R.yml
  data/cisagov_S.yml
  data/cisagov_T.yml
  data/cisagov_U.yml
  data/cisagov_V.yml
  data/cisagov_W.yml
  data/cisagov_X.yml
  data/cisagov_Y.yml
  data/cisagov_Z.yml
Labels: bug
